### ISSUE TITLE
socranop-installtool --post-install occasionally aborts connecting to D-Bus

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#43] opened 2021-07-16 12:53 UTC
In my local installs to the pipenv/`$HOME` combination, I often `git checkout` another branch, and then run `pipenv run socranop-installtool --post-install` (or rather, I run `socranop-installtool --post-install` from inside a `pipenv shell`).

Occasionally, this happens:

```
[user@host socranop]$ socranop-installtool --post-install
Socranop Installation
=====================

Python library dependencies: Checking
  [load] module gi: OK
  [load] gi module GLib: OK
  [find] gi module Gtk version 3.0: OK
  [load] gi module Gtk: OK
  [load] gi module Gio: OK
  [find] gi module GUdev version 1.0: OK
  [load] gi module GUdev: OK
  [load] module pydbus: OK
  [load] module usb.core: OK
  [check] finding any usb device: OK
Python library dependencies: OK
Bash completion: Installing files
  [inst] /home/user/.local/share/bash-completion/completions/socranop-ctl
  [inst] /home/user/.local/share/bash-completion/completions/socranop-gui
  [inst] /home/user/.local/share/bash-completion/completions/socranop-installtool
  [inst] /home/user/.local/share/bash-completion/completions/socranop-session-service
Bash completion: Install completed
Dbus service: Stopping old service
  [stop] Shutting down version 0.4.92: OK
Dbus service: Installing files
  [inst] /home/user/.local/share/dbus-1/services/io.github.socratools.socranop.service
Dbus service: Install completed
Dbus service: Verifying
  [verify] Reload dbus to register the new service: OK
  [verify] Checking for registered service: OK
  [verify] Starting D-Bus service: ERROR
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected (4)
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/socranop-buNqeWKb/bin/socranop-installtool", line 33, in <module>
    sys.exit(load_entry_point('socranop', 'console_scripts', 'socranop-installtool')())
  File "/home/user/proj/socratools/socranop/socranop/installtool.py", line 1046, in main
    everything.post_install()
  File "/home/user/proj/socratools/socranop/socranop/installtool.py", line 952, in post_install
    thing.post_install()
  File "/home/user/proj/socratools/socranop/socranop/installtool.py", line 677, in post_install
    self.verify_install()
  File "/home/user/proj/socratools/socranop/socranop/installtool.py", line 727, in verify_install
    service_version = our_service.version
  File "/home/user/.local/share/virtualenvs/socranop-buNqeWKb/lib/python3.9/site-packages/pydbus/proxy_property.py", line 22, in __get__
    return instance._object["org.freedesktop.DBus.Properties"].Get(self._iface_name, self.__name__)
  File "/home/user/.local/share/virtualenvs/socranop-buNqeWKb/lib/python3.9/site-packages/pydbus/proxy_method.py", line 72, in __call__
    ret = instance._bus.con.call_sync(
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected (4)
[user@host socranop]$ 
```

Immediately repeating the `socranop-installtool --post-install` command will then work:

```
[user@host socranop]$ socranop-installtool --post-install
Socranop Installation
=====================

Python library dependencies: Checking
  [load] module gi: OK
  [load] gi module GLib: OK
  [find] gi module Gtk version 3.0: OK
  [load] gi module Gtk: OK
  [load] gi module Gio: OK
  [find] gi module GUdev version 1.0: OK
  [load] gi module GUdev: OK
  [load] module pydbus: OK
  [load] module usb.core: OK
  [check] finding any usb device: OK
Python library dependencies: OK
Bash completion: Installing files
  [inst] /home/user/.local/share/bash-completion/completions/socranop-ctl
  [inst] /home/user/.local/share/bash-completion/completions/socranop-gui
  [inst] /home/user/.local/share/bash-completion/completions/socranop-installtool
  [inst] /home/user/.local/share/bash-completion/completions/socranop-session-service
Bash completion: Install completed
Dbus service: Installing files
  [inst] /home/user/.local/share/dbus-1/services/io.github.socratools.socranop.service
Dbus service: Install completed
Dbus service: Verifying
  [verify] Reload dbus to register the new service: OK
  [verify] Checking for registered service: OK
  [verify] Starting D-Bus service: 0.4.92
  [verify] Installtool version: 0.4.92
  [verify] Shutting down session D-Bus service: OK
Dbus service: Complete
Man pages: Installing files
  [inst] /home/user/.local/share/man/man1/socranop-ctl.1
  [inst] /home/user/.local/share/man/man1/socranop-gui.1
  [inst] /home/user/.local/share/man/man1/socranop-session-service.1
Man pages: Install completed
XDG application launcher: Installing files
  [inst] /home/user/.local/share/applications/io.github.socratools.socranop.desktop
  [inst] /home/user/.local/share/icons/hicolor/16x16/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/24x24/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/32x32/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/48x48/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/64x64/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/96x96/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/128x128/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/192x192/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/256x256/apps/io.github.socratools.socranop.png
  [inst] /home/user/.local/share/icons/hicolor/scalable/apps/io.github.socratools.socranop.svg
XDG application launcher: Install completed
Udev rules: Installing files
  [inst] /etc/udev/rules.d/70-socranop.rules
Udev rules: Install completed

Socranop installation has completed successfully

You should probably run the following commands with sudo:
------------------------------------------------------------------------
#!/bin/sh
# This script contains commands which socranop-installtool could not run.
# You might have better luck running them manually, probably via sudo.

# udev rules allowing non-root access to the USB device
cat>/etc/udev/rules.d/70-socranop.rules<<EOF
# Soundcraft Notepad series mixers with audio routing controlled by USB
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="05fc", ATTRS{idProduct}=="0030", TAG+="uaccess"
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="05fc", ATTRS{idProduct}=="0031", TAG+="uaccess"
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="05fc", ATTRS{idProduct}=="0032", TAG+="uaccess"
EOF

# Trigger udev rules which run when adding existing mixer devices
sleep 4   # wait until udev should have noticed the new rules
for product_id in 0030 0031 0032
do
    udevadm trigger --verbose \
        --action=add --subsystem-match=usb \
        --attr-match=idVendor=05fc --attr-match=idProduct=${product_id}
done
------------------------------------------------------------------------

Finally, run `socranop-gui` or `socranop-ctl` as a regular user.
```

I am not certain why occasionally a leftover `socranop-session-service´ process behaves that strangely.

**Comment by lack** [comment] 2021-07-16 23:51
This is the issue I root-caused and fixed in #41

The issue is that in the installer we have a shutdown of the old service, followed immediately by an attempt to use bus activation to start the new service.

If there's a delay between when the shutdown API is called and when the service truly disappears from the bus, that bus activation may catch the old service just as it dies, instead of launching the new process, causing this error.

The fix in #41 adds an explicit wait in the shutdown code to make sure the old service is completely free of the bus, guaranteeing that the subsequent service activation will never catch the old service by mistake.

**Closed** 2021-07-16 23:51 UTC
